### Create Funding
POST http://localhost:8080/api/funding
Content-Type: application/json

{
  "title": "의성 대잔치",
  "description": "의성에서 벌어지는 영포티들의 유쾌한 반란",
  "author": "holden",
  "age": "20대",
  "size": "20",
  "gender": "여성",
  "region": "서울",
  "budget": 500000
}

> {%
    client.global.set("fundingId", response.body.message)
%}

###

### Get Funding by ID
GET http://localhost:8080/api/funding/{{fundingId}}

###

### Get All Fundings
GET http://localhost:8080/api/funding

###

### Delete Funding
DELETE http://localhost:8080/api/funding/{{fundingId}}


### Delete All Fundings
DELETE http://localhost:8080/api/funding

### Join Funding
POST http://localhost:8080/api/funding/{{fundingId}}/join
Content-Type: application/json

{
  "participantId": "yongjae",
  "fee": 100000
}