name: Deploy to Cloud Run

on:
  push:
    branches: [main] # 또는 배포 브랜치 지정

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: decent-destiny-463614-g6

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform=linux/amd64 \
            -f june/Dockerfile \
            -t us-central1-docker.pkg.dev/decent-destiny-463614-g6/spring-app-repo/june-app:latest \
            --push .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy june-app \
            --image=us-central1-docker.pkg.dev/decent-destiny-463614-g6/spring-app-repo/june-app:latest \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080 \
            --timeout=300s \
            --service-account=github-action@decent-destiny-463614-g6.iam.gserviceaccount.com

#    gcloud run deploy june-app \
#    --image=us-central1-docker.pkg.dev/decent-destiny-463614-g6/spring-app-repo/june-app:latest \
#    --region=us-central1 \
#    --platform=managed \
#    --allow-unauthenticated \
#    --port=8080 \
#    --timeout=300s \
#    --service-account=my-cloud-run-sa@decent-destiny-463614-g6.iam.gserviceaccount.com
